# Generated by Django 5.1.7 on 2025-03-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantimage',
            options={'verbose_name': 'Рисунок растения', 'verbose_name_plural': 'Рисунки растений'},
        ),
        migrations.AddField(
            model_name='plant',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=50, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sku',
            field=models.CharField(max_length=15, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to='images/plants/', verbose_name='Рисунок'),
        ),
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.plant', verbose_name='Рисунок'),
        ),
    ]
